language: ruby
rvm:
 - 2.4
dist: trusty
addons:
    postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql -c 'create database "destinder-api_test";' -U postgres
script:
  - bundle exec rails db:setup db:migrate
